const referenceSkills = [
  // Programming Languages
  "JavaScript",
  "React",
  "Node.js",
  "Python",
  "Java",
  "C++",
  "C#",
  "PHP",
  "Ruby",
  "Go",
  "Swift",
  "Kotlin",
  "Scala",
  "Assembly",
  "SQL",
  "PL/SQL",
  "T-SQL",

  // Web Development
  "HTML",
  "CSS",
  "Bootstrap",
  "Tailwind CSS",
  "Material UI",
  "Angular",
  "Vue.js",
  "Express.js",
  "Django",
  "Flask",
  "Laravel",
  "Spring Boot",

  // Data Science & Machine Learning
  "TensorFlow",
  "PyTorch",
  "Scikit-learn",
  "Pandas",
  "NumPy",
  "Matplotlib",
  "Seaborn",
  "Jupyter Notebook",
  "Spark",
  "Hadoop",
  "Machine Learning",
  "Deep Learning",
  "Natural Language Processing",

  // Cloud Computing & DevOps
  "AWS",
  "Azure",
  "GCP",
  "Docker",
  "Kubernetes",
  "Jenkins",
  "Git",
  "GitHub",
  "CI/CD",
  "Infrastructure as Code (IaC)",
  "Serverless Computing",
  "DevOps",

  // Database Management
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "Oracle Database",
  "SQL Server",
  "NoSQL",

  // Networking & Security
  "TCP/IP",
  "OSI Model",
  "Networking Protocols",
  "Firewalls",
  "VPN",
  "Cybersecurity",

  // System Administration & Operations
  "Linux",
  "Windows Server",
  "VMware",
  "Virtualization",
  "Cloud Management",
  "System Monitoring",
  "Disaster Recovery",

  // Business & Soft Skills
  "Communication",
  "Leadership",
  "Teamwork",
  "Problem Solving",
  "Critical Thinking",
  "Project Management",
  "Time Management",
  "Adaptability",
  "Creativity",
  "Interpersonal Skills",
];
module.exports = referenceSkills;
